### ISSUE TITLE
SRB decouplers not decoupling

### ISSUE THREAD

**Issue by Nemo2507** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#10]
So I was using the OPS1 script during the ascent, everything went normally until SRB separation. The top and bottom motors fired and the decouplers were in the same stage, but it didn't separate. So I tested them on the ground with methods like directly clicking on it and clicking the decouple but that still didn't work, even when I clicked decouple, I can still see the SRB GUI. I tested with the new shuttle I remade since the new update, and I even tested with the old save I had but nothing worked, it still won't separate

**Comment by giuliodondi** [comment]
Please make sure you did not accidentally attach the SRBs directly to the ET instead of the decouplers.
I'll point out that with the latest update there are attach nodes to snap the decouplers to the ET in the right place and the SRBS to the decouplers themselves, there's no longer any need to manually surface-aling everything

**Comment by giuliodondi** [comment]
I've just assembled the Shuttle from scratch and tested, I could not reproduce your issue.

Please make sure you did not accidentally attach the SRBs directly to the ET instead of the decouplers.
I'll point out that with the latest update there are attach nodes to snap the decouplers to the ET in the right place and the SRBS to the decouplers themselves, there's no longer any need to manually surface-aling everything.

If the problem persists, post screenshots of how you assembled your vehicle and maybe a video illustrating your issue

**Comment by Nemo2507** [comment]
Thank you, it worked. I initially can't get the decouplers on to the external tank node properly, so I attached them using snap and I did not know that the node was meant for the decouplers, so I accidentally attached the SRBs on to them.

**Comment by giuliodondi** [comment]
I'll soon release another update and I'll include proper assembly instructions
