### ISSUE TITLE
Craft file?

### ISSUE THREAD

**Issue by KnedlikMCPE** [giuliodondi/Space-Shuttle-System-realistic-aerodynamics#14]
Hi, would it be possible to publish a craft file for a basic shuttle assembly without payload?
Thanks.

**Comment by KnedlikMCPE** [comment]
Because for example the booster assembly is a bit confusing. I got multiple shuttle booster parts that are essentially identical, and neither of them has sensible nodes.

**Comment by giuliodondi** [comment]
No because, as the readme says, some updates can be craft-breaking.

Craft files save the configuration of certain part modules, so if I package the craft file, people will keep using it and possibly have a broken mod.

The SRB parts intended for this mod can be found by searching for "RSRM" and are distinctly different from say Real-Scale Booster parts or others
